discovery:
  alibaba_cloud:
    access_key_id: ''
    access_key_secret: ''
    enabled: false
    region: cn-hangzhou
    services:
    - oss
    - rds
    - polardb
    - mongodb
    - redis
  aws:
    enabled: false
    regions:
    - us-east-1
    - us-west-2
    services:
    - s3
    - rds
    - dynamodb
    - redshift
    - athena
    - glue
    - emr
    - kinesis
    - msk
    - documentdb
    - neptune
    - timestream
    - qldb
    - opensearch
    - elasticache
  azure:
    enabled: false
    services:
    - blob_storage
    - sql_database
    - cosmos_db
    - synapse
    - data_factory
    - event_hub
    - service_bus
  data_lakes:
    data_lake_connections: null
    enabled: false
  data_warehouses:
    enabled: false
    warehouse_connections: null
  databases:
    connection_timeout: 30
    database_connections: null
    enabled: false
  file_system:
    enabled: true
    file_extensions:
    - .csv
    - .json
    - .xlsx
    - .parquet
    - .sql
    - .db
    - .sqlite
    max_file_size_mb: 1000
    scan_paths:
    - /data
    - /home/user/documents
    - /opt/databases
  gcp:
    enabled: true
    project_id: bank-edw-datalake
    service_account_json: '{"type": "service_account", "project_id": "bank-edw-datalake",
      "private_key_id": "aa53c9f889374aacb74eaf95f45396d02cca1907", "private_key":
      "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIDNmE8RmbJnDA\nchWnEn+LduTL+ottlv3rY6rvIlgNZH5m8hrjL8ZmQMh7YERjFPYakbVVvfBgon3E\nytM0IzUOK0+NH7pIwMKis7+DevnxuKccwW78MjEOUbbB9Ffpgf21WDosJdRWAllf\nmKF2khhT9pyh8KqPYqKzlanf/38I54rW6sEcFJNw4StXnHwQkL8wGuNefGFZNWe7\nFoHVSRhqlY8/9egzfBOEs+ezDO6ZCMzEr/crL1vnwKwmollgvGSZ3mO4C8ShxLsF\nf10cJso49/FI92yym0vgGsBLW+edgKFKnj8s/bL1ZvimXZjWavZpEurrdoyHQEl0\nSa/9OxgvAgMBAAECggEAJRIggt6syI/0h+z8LzQh14XGOzhn+vxmfGbBR8Qc/gpX\n1BrcOapiQROTMy2xLo01V9IVgNiMQVQLK1sMjVZS4BfNi5DME+xIhR77B9HTnGQD\n77O2rdxdM9KXo9R0MAzLJ348dW7jLLcNucXOcer7wB9sgiPXb2+vR8kdrCkr8Mmn\nUdJjK9qsY1bEtD9i9C3vXLP9+egQxS4iTPQ2fFn+BWo7VkaOtxnCOlAzCgk2wDcH\nMc0/iNitX7HbljBIoBdwM4PBhrA/uu4OaOIAuLUEUjTyaem9mu2EDPZzapgiGgLw\nB0B6lt0vmP3LNPkok0yZ78IY3XXk7HMDoBf7MdewuQKBgQD07EEmy26mbEXVHfqL\nx5yK1YEd6JWT2HrSZwL1jS4/9zeEvRvTpM/hn2bnqr5Er95YMswmzHBKiC7lM7cl\nVGB+Et3R/ABEagQf9pa11ieZiK5IOLuw3EAsLb60btJvJUoKXMKE82aTug9XGIcB\nqtKb9njE1pLAmNthLktZ5MksKQKBgQDRGQ3bZ0e/gdDTPJ0Ii8yjLS1rPg+j+0l+\nAIm7QYdNXrxYbm2VlORCa6cLWODaw5imfV7GLRmD7ryNU71ZSbA+c3D8Qs+YOTuA\nqE5hgaLh6OmDpna0CMvxFyP/nQNLoWQm7gQpSR6/kb0qtnYWaDScVajGfB8ITmQ7\nL/aSroMslwKBgQDupe3t0Tdl7gY1XNqurLd6CAOhkul8f+ldboZRoVk5dregHWwp\n02PDosBwZ8yxvPPX2NdXzshztzKKntOMCiVjcxq06umPwAV455t+XseDMM0xDibE\ndDgLVB+ITJu7NQhqBGx9g3Wl6Bveb8XM+BfzZDvVAIdKJydMEAHX+7eR0QKBgGmR\nfK2JN3A42nXL5HysGGVKKeQ7MSpZdIFpRCCGtQkbC3yaRDmBMr1WHMBd3yiUGD32\njiMAIiG6JvgzjyXFTnY5UpIKKUVxn9kVIH2aNeJY9YzCPqwmxNC0HjivzToiAa6l\n/PPbNusBacBm3rfxZJ6JoOyVPhWzfmdjj9n+wbuBAoGBAOAG4witPgfXMRcNm1IW\nefRcQ9C8/O6XKtD1rZ8LzF4TYidf6lUUEKuIW4lou9aDmBF26CcwEDJo9meiZeVc\nBTioTf7Vify+mBNA3q9rfiIIOfXsWHYmcNLsvsPchb6Nk2TDtAAy/1dk5tpVvLnu\nnmjDZ4vadlKrqChRZRgAWP9C\n-----END
      PRIVATE KEY-----\n", "client_email": "consentmanagement@bank-edw-datalake.iam.gserviceaccount.com",
      "client_id": "110447367815618472567", "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url":
      "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/consentmanagement%40bank-edw-datalake.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"}'
    services:
    - bigquery
  ibm_cloud:
    api_key: ''
    enabled: false
    region: us-south
    resource_group_id: ''
    services:
    - cloud_object_storage
    - db2
    - cloudant
    - watson_discovery
  max_concurrent_scans: 10
  monitoring:
    batch_size: 100
    enabled: true
    real_time_watching: true
    watch_interval: 5
  network:
    connection_timeout: 30
    enabled: false
    file_extensions:
    - .csv
    - .json
    - .xlsx
    - .parquet
    - .sql
    - .txt
    - .xml
    - .log
    max_file_size_mb: 1000
    network_sources: null
  oracle_cloud:
    compartment_id: ''
    enabled: false
    region: us-ashburn-1
    services:
    - object_storage
    - autonomous_database
    - mysql
    - nosql
  saas_platforms:
    enabled: false
    saas_connections: null
  scan_interval: 60
  streaming_platforms:
    enabled: false
    streaming_connections: null
logging:
  file: data_discovery.log
  level: INFO
  max_size_mb: 100
metadata:
  detect_pii: true
  extract_samples: true
  extract_schema: true
  sample_size: 100
